// Copyright 2021 OpenSSF Scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cron/data/metadata.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardLoc      *string                `protobuf:"bytes,1,opt,name=shard_loc,json=shardLoc,proto3,oneof" json:"shard_loc,omitempty"`
	NumShard      *int32                 `protobuf:"varint,2,opt,name=num_shard,json=numShard,proto3,oneof" json:"num_shard,omitempty"`
	CommitSha     *string                `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3,oneof" json:"commit_sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardMetadata) Reset() {
	*x = ShardMetadata{}
	mi := &file_cron_data_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardMetadata) ProtoMessage() {}

func (x *ShardMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cron_data_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardMetadata.ProtoReflect.Descriptor instead.
func (*ShardMetadata) Descriptor() ([]byte, []int) {
	return file_cron_data_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ShardMetadata) GetShardLoc() string {
	if x != nil && x.ShardLoc != nil {
		return *x.ShardLoc
	}
	return ""
}

func (x *ShardMetadata) GetNumShard() int32 {
	if x != nil && x.NumShard != nil {
		return *x.NumShard
	}
	return 0
}

func (x *ShardMetadata) GetCommitSha() string {
	if x != nil && x.CommitSha != nil {
		return *x.CommitSha
	}
	return ""
}

var File_cron_data_metadata_proto protoreflect.FileDescriptor

const file_cron_data_metadata_proto_rawDesc = "" +
	"\n" +
	"\x18cron/data/metadata.proto\x12!ossf.scorecard.cron.internal.data\"\xa2\x01\n" +
	"\rShardMetadata\x12 \n" +
	"\tshard_loc\x18\x01 \x01(\tH\x00R\bshardLoc\x88\x01\x01\x12 \n" +
	"\tnum_shard\x18\x02 \x01(\x05H\x01R\bnumShard\x88\x01\x01\x12\"\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tH\x02R\tcommitSha\x88\x01\x01B\f\n" +
	"\n" +
	"_shard_locB\f\n" +
	"\n" +
	"_num_shardB\r\n" +
	"\v_commit_shaB+Z)github.com/ossf/scorecard-infra/cron/datab\x06proto3"

var (
	file_cron_data_metadata_proto_rawDescOnce sync.Once
	file_cron_data_metadata_proto_rawDescData []byte
)

func file_cron_data_metadata_proto_rawDescGZIP() []byte {
	file_cron_data_metadata_proto_rawDescOnce.Do(func() {
		file_cron_data_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cron_data_metadata_proto_rawDesc), len(file_cron_data_metadata_proto_rawDesc)))
	})
	return file_cron_data_metadata_proto_rawDescData
}

var file_cron_data_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cron_data_metadata_proto_goTypes = []any{
	(*ShardMetadata)(nil), // 0: ossf.scorecard.cron.internal.data.ShardMetadata
}
var file_cron_data_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cron_data_metadata_proto_init() }
func file_cron_data_metadata_proto_init() {
	if File_cron_data_metadata_proto != nil {
		return
	}
	file_cron_data_metadata_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cron_data_metadata_proto_rawDesc), len(file_cron_data_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cron_data_metadata_proto_goTypes,
		DependencyIndexes: file_cron_data_metadata_proto_depIdxs,
		MessageInfos:      file_cron_data_metadata_proto_msgTypes,
	}.Build()
	File_cron_data_metadata_proto = out.File
	file_cron_data_metadata_proto_goTypes = nil
	file_cron_data_metadata_proto_depIdxs = nil
}
