// Copyright 2021 OpenSSF Scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cron/data/request.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Commit        *string                `protobuf:"bytes,3,opt,name=commit,proto3,oneof" json:"commit,omitempty"`
	Metadata      []string               `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_cron_data_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_cron_data_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_cron_data_request_proto_rawDescGZIP(), []int{0}
}

func (x *Repo) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Repo) GetCommit() string {
	if x != nil && x.Commit != nil {
		return *x.Commit
	}
	return ""
}

func (x *Repo) GetMetadata() []string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScorecardBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*Repo                `protobuf:"bytes,4,rep,name=repos,proto3" json:"repos,omitempty"`
	ShardNum      *int32                 `protobuf:"varint,2,opt,name=shard_num,json=shardNum,proto3,oneof" json:"shard_num,omitempty"`
	JobTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=job_time,json=jobTime,proto3,oneof" json:"job_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScorecardBatchRequest) Reset() {
	*x = ScorecardBatchRequest{}
	mi := &file_cron_data_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScorecardBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScorecardBatchRequest) ProtoMessage() {}

func (x *ScorecardBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_data_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScorecardBatchRequest.ProtoReflect.Descriptor instead.
func (*ScorecardBatchRequest) Descriptor() ([]byte, []int) {
	return file_cron_data_request_proto_rawDescGZIP(), []int{1}
}

func (x *ScorecardBatchRequest) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *ScorecardBatchRequest) GetShardNum() int32 {
	if x != nil && x.ShardNum != nil {
		return *x.ShardNum
	}
	return 0
}

func (x *ScorecardBatchRequest) GetJobTime() *timestamppb.Timestamp {
	if x != nil {
		return x.JobTime
	}
	return nil
}

var File_cron_data_request_proto protoreflect.FileDescriptor

const file_cron_data_request_proto_rawDesc = "" +
	"\n" +
	"\x17cron/data/request.proto\x12!ossf.scorecard.cron.internal.data\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n" +
	"\x04Repo\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x88\x01\x01\x12\x1b\n" +
	"\x06commit\x18\x03 \x01(\tH\x01R\x06commit\x88\x01\x01\x12\x1a\n" +
	"\bmetadata\x18\x02 \x03(\tR\bmetadataB\x06\n" +
	"\x04_urlB\t\n" +
	"\a_commit\"\xd5\x01\n" +
	"\x15ScorecardBatchRequest\x12=\n" +
	"\x05repos\x18\x04 \x03(\v2'.ossf.scorecard.cron.internal.data.RepoR\x05repos\x12 \n" +
	"\tshard_num\x18\x02 \x01(\x05H\x00R\bshardNum\x88\x01\x01\x12:\n" +
	"\bjob_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\ajobTime\x88\x01\x01B\f\n" +
	"\n" +
	"_shard_numB\v\n" +
	"\t_job_timeJ\x04\b\x01\x10\x02B+Z)github.com/ossf/scorecard-infra/cron/datab\x06proto3"

var (
	file_cron_data_request_proto_rawDescOnce sync.Once
	file_cron_data_request_proto_rawDescData []byte
)

func file_cron_data_request_proto_rawDescGZIP() []byte {
	file_cron_data_request_proto_rawDescOnce.Do(func() {
		file_cron_data_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cron_data_request_proto_rawDesc), len(file_cron_data_request_proto_rawDesc)))
	})
	return file_cron_data_request_proto_rawDescData
}

var file_cron_data_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cron_data_request_proto_goTypes = []any{
	(*Repo)(nil),                  // 0: ossf.scorecard.cron.internal.data.Repo
	(*ScorecardBatchRequest)(nil), // 1: ossf.scorecard.cron.internal.data.ScorecardBatchRequest
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_cron_data_request_proto_depIdxs = []int32{
	0, // 0: ossf.scorecard.cron.internal.data.ScorecardBatchRequest.repos:type_name -> ossf.scorecard.cron.internal.data.Repo
	2, // 1: ossf.scorecard.cron.internal.data.ScorecardBatchRequest.job_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cron_data_request_proto_init() }
func file_cron_data_request_proto_init() {
	if File_cron_data_request_proto != nil {
		return
	}
	file_cron_data_request_proto_msgTypes[0].OneofWrappers = []any{}
	file_cron_data_request_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cron_data_request_proto_rawDesc), len(file_cron_data_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cron_data_request_proto_goTypes,
		DependencyIndexes: file_cron_data_request_proto_depIdxs,
		MessageInfos:      file_cron_data_request_proto_msgTypes,
	}.Build()
	File_cron_data_request_proto = out.File
	file_cron_data_request_proto_goTypes = nil
	file_cron_data_request_proto_depIdxs = nil
}
